runtime: python312
entrypoint: gunicorn -b :$PORT app:app

env_variables:
  DB_USER: "flaskuser"
  DB_PASS: "pass"
  DB_NAME: "disasterdb"
  CLOUD_SQL_CONNECTION_NAME: "project:region:instance"

automatic_scaling:
  target_cpu_utilization: 0.65
  max_instances: 15
